### ISSUE TITLE
Remove translation CLA

### ISSUE THREAD

**Issue by comradekingu** [ondrejnedoma/voyalert#4]
https://hosted.weblate.org/contributor-agreement/voyalert/translation?next=/projects/voyalert/translation/
is superfluous to 6.4 in https://hosted.weblate.org/legal/terms/

The other info can go in the info field.

Can be fixed in
https://hosted.weblate.org/settings/voyalert/translation/

**Comment by ondrejnedoma** [comment]
Fixed.

**Comment by comradekingu** [comment]
I don't agree to any CLAs. Not sure what the current one actually does.
For anyone malicious it seems superfluous, and I can't see it changing behavior for
anyone knowing not to be fluent any more so than it does in the info field.
Edit: It is at best a hurdle for contributions.

**Comment by ondrejnedoma** [comment]
I thought the agreement was a required field. Apparently it's not so I'll just leave it empty then.
